### ISSUE TITLE
Examples don`t work correctly

### ISSUE THREAD

**Issue by Kupchanski** [genforce/idinvert_pytorch#2]
I tried to test inversion.py example, but got this mistake.
![image](https://user-images.githubusercontent.com/13433909/88376192-5a3e5d80-cdb6-11ea-97ef-cb4749536fd4.png)

It seems like it just need to be corrected a little.
TY for pytorch realization btw! Love it

**Comment by ShenYujun** [comment]
Please try
```
cd idinvert_pytorch
python invert.py
```

We use relative path to find the images.

**Comment by Kupchanski** [comment]
> Please try
> 
> ```
> cd idinvert_pytorch
> python invert.py
> ```
> 
> We use relative path to find the images.

Thanks, It works now!

Another question. If I need this alg for 1024 res, I need to train encoder from scratch?

**Comment by ShenYujun** [comment]
Yes.

**Comment by ak9250** [comment]
@ShenYujun i am getting same issue when doing diffusion in colab
Context ID:  67% 2/3 [00:12<00:06,  6.47s/it]Traceback (most recent call last):
  File "diffuse.py", line 146, in <module>
    main()
  File "diffuse.py", line 131, in main
    num_viz=args.num_results)
  File "/content/idinvert_pytorch/utils/inverter.py", line 313, in easy_diffuse
    self.preprocess(context),
  File "/content/idinvert_pytorch/utils/inverter.py", line 105, in preprocess
    raise ValueError(f'Input image should be with type `numpy.ndarray`!')
ValueError: Input image should be with type `numpy.ndarray`!

**Comment by ShenYujun** [comment]
How do you load the images and how do you feed them to the function `easy_diffuse()`?
